name = "studio"
compatibility_date = "2024-06-17"

# Build configuration
[build]
command = "npm run build"

# Production branch
[pages]
branch = "main"

# Environment variables for production
[env.production.vars]
TO_EMAIL = "support@isolated.tech"
FROM_EMAIL = "noreply@isolated.tech"

# Preview deployments
[pages.preview]
branch = ["dev", "feature/*"]